services:
  - type: web
    name: s2e-earning-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_UPI
        sync: false
      - key: SUPPORT_USERNAME
        sync: false
      - key: DATABASE_URL
        sync: false
